################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_acmp.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_burtc.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_cmu.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_core.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_dbg.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_emu.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_eusart.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_gpcrc.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_gpio.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_i2c.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_iadc.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_ldma.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_letimer.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_msc.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_opamp.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_pcnt.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_prs.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_rmu.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_se.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_system.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_timer.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_usart.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_vdac.c \
E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_wdog.c 

OBJS += \
./gecko_sdk_4.4.3/platform/emlib/src/em_acmp.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_burtc.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_cmu.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_core.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_dbg.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_emu.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_eusart.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_gpcrc.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_gpio.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_i2c.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_iadc.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_ldma.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_letimer.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_msc.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_opamp.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_pcnt.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_prs.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_rmu.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_se.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_system.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_timer.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_usart.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_vdac.o \
./gecko_sdk_4.4.3/platform/emlib/src/em_wdog.o 

C_DEPS += \
./gecko_sdk_4.4.3/platform/emlib/src/em_acmp.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_burtc.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_cmu.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_core.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_dbg.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_emu.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_eusart.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_gpcrc.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_gpio.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_i2c.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_iadc.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_ldma.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_letimer.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_msc.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_opamp.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_pcnt.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_prs.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_rmu.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_se.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_system.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_timer.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_usart.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_vdac.d \
./gecko_sdk_4.4.3/platform/emlib/src/em_wdog.d 


# Each subdirectory must supply rules for building sources it contributes
gecko_sdk_4.4.3/platform/emlib/src/em_acmp.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_acmp.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_acmp.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_burtc.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_burtc.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_burtc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_cmu.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_cmu.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_cmu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_core.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_core.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_core.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_dbg.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_dbg.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_dbg.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_emu.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_emu.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_emu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_eusart.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_eusart.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_eusart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_gpcrc.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_gpcrc.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_gpcrc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_gpio.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_gpio.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_gpio.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_i2c.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_i2c.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_i2c.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_iadc.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_iadc.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_iadc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_ldma.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_ldma.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_ldma.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_letimer.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_letimer.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_letimer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_msc.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_msc.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_msc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_opamp.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_opamp.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_opamp.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_pcnt.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_pcnt.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_pcnt.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_prs.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_prs.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_prs.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_rmu.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_rmu.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_rmu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_se.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_se.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_se.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_system.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_system.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_system.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_timer.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_timer.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_timer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_usart.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_usart.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_usart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_vdac.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_vdac.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_vdac.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.3/platform/emlib/src/em_wdog.o: E:/SiliconLabs/SDKs2/gecko_sdk/platform/emlib/src/em_wdog.c gecko_sdk_4.4.3/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DEFR32MG24B310F1536IM48=1' '-DSE_MANAGER_CONFIG_FILE="btl_aes_ctr_stream_block_cfg.h"' '-DBOOTLOADER_ENABLE=1' '-DBOOTLOADER_SECOND_STAGE=1' '-DSL_RAMFUNC_DISABLE=1' '-D__START=main' '-D__STARTUP_CLEAR_BSS=1' '-DBOOTLOADER_SUPPORT_INTERNAL_STORAGE=1' '-DBOOTLOADER_SUPPORT_STORAGE=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=39000000' '-DSL_BOARD_NAME="BRD2601B"' '-DSL_BOARD_REV="A01"' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DMBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>' '-DMBEDTLS_PSA_CRYPTO_CLIENT=1' '-DMBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>' '-DSL_TRUSTZONE_SECURE=1' -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\config" -I"E:\SiliconLabs\project\DevKit_bootloader-storage-internal-single1Mb\autogen" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/Device/SiliconLabs/EFR32MG24/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/debug" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/parser" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/api" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/core/flash" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/bootloader/security" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/CMSIS/Core/Include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/emlib/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/config/preset" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_mbedtls_support/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/mbedtls/library" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/sl_psa_driver/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/security/sl_component/se_manager/src" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/silicon_labs/silabs_core/memory_manager" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/lib/fih/inc" -I"E:/SiliconLabs/SDKs2/gecko_sdk//util/third_party/trusted-firmware-m/platform/include" -I"E:/SiliconLabs/SDKs2/gecko_sdk//platform/common/toolchain/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -Wno-ignored-qualifiers -Wno-sign-compare --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.3/platform/emlib/src/em_wdog.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


